#############################################################################
# Makefile for building: Notatio-Antiqua
# Generated by qmake (2.01a) (Qt 4.7.0) on: So. Nov 28 22:36:05 2010
# Project:  Notatio-Antiqua.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Notatio-Antiqua.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		naclefselect.cpp \
		naheaderwizard.cpp \
		nahelp.cpp \
		namdi.cpp \
		naprog.cpp \
		nasettings.cpp \
		nasyntax.cpp moc_naclefselect.cpp \
		moc_naheaderwizard.cpp \
		moc_nahelp.cpp \
		moc_namdi.cpp \
		moc_naprog.cpp \
		moc_nasettings.cpp \
		moc_nasyntax.cpp \
		qrc_naprog.cpp
OBJECTS       = main.o \
		naclefselect.o \
		naheaderwizard.o \
		nahelp.o \
		namdi.o \
		naprog.o \
		nasettings.o \
		nasyntax.o \
		moc_naclefselect.o \
		moc_naheaderwizard.o \
		moc_nahelp.o \
		moc_namdi.o \
		moc_naprog.o \
		moc_nasettings.o \
		moc_nasyntax.o \
		qrc_naprog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Notatio-Antiqua.pro
QMAKE_TARGET  = Notatio-Antiqua
DESTDIR       = 
TARGET        = Notatio-Antiqua

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_naclefselect.h ui_naheaderwizard.h ui_nahelp.h ui_naprog.h ui_nasettings.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Notatio-Antiqua.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile Notatio-Antiqua.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Notatio-Antiqua.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Notatio-Antiqua1.0.0 || $(MKDIR) .tmp/Notatio-Antiqua1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Notatio-Antiqua1.0.0/ && $(COPY_FILE) --parents naclefselect.h naheaderwizard.h nahelp.h namdi.h naprog.h nasettings.h nasyntax.h .tmp/Notatio-Antiqua1.0.0/ && $(COPY_FILE) --parents naprog.qrc .tmp/Notatio-Antiqua1.0.0/ && $(COPY_FILE) --parents main.cpp naclefselect.cpp naheaderwizard.cpp nahelp.cpp namdi.cpp naprog.cpp nasettings.cpp nasyntax.cpp .tmp/Notatio-Antiqua1.0.0/ && $(COPY_FILE) --parents naclefselect.ui naheaderwizard.ui nahelp.ui naprog.ui nasettings.ui .tmp/Notatio-Antiqua1.0.0/ && $(COPY_FILE) --parents NaProg-de.ts NaProg-en.ts NaProg-fr.ts .tmp/Notatio-Antiqua1.0.0/ && (cd `dirname .tmp/Notatio-Antiqua1.0.0` && $(TAR) Notatio-Antiqua1.0.0.tar Notatio-Antiqua1.0.0 && $(COMPRESS) Notatio-Antiqua1.0.0.tar) && $(MOVE) `dirname .tmp/Notatio-Antiqua1.0.0`/Notatio-Antiqua1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Notatio-Antiqua1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_naclefselect.cpp moc_naheaderwizard.cpp moc_nahelp.cpp moc_namdi.cpp moc_naprog.cpp moc_nasettings.cpp moc_nasyntax.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_naclefselect.cpp moc_naheaderwizard.cpp moc_nahelp.cpp moc_namdi.cpp moc_naprog.cpp moc_nasettings.cpp moc_nasyntax.cpp
moc_naclefselect.cpp: naclefselect.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) naclefselect.h -o moc_naclefselect.cpp

moc_naheaderwizard.cpp: naheaderwizard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) naheaderwizard.h -o moc_naheaderwizard.cpp

moc_nahelp.cpp: ui_nahelp.h \
		nahelp.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) nahelp.h -o moc_nahelp.cpp

moc_namdi.cpp: nasyntax.h \
		namdi.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) namdi.h -o moc_namdi.cpp

moc_naprog.cpp: nasyntax.h \
		nasettings.h \
		nahelp.h \
		ui_nahelp.h \
		namdi.h \
		naclefselect.h \
		naheaderwizard.h \
		naprog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) naprog.h -o moc_naprog.cpp

moc_nasettings.cpp: nasettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) nasettings.h -o moc_nasettings.cpp

moc_nasyntax.cpp: nasyntax.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) nasyntax.h -o moc_nasyntax.cpp

compiler_rcc_make_all: qrc_naprog.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_naprog.cpp
qrc_naprog.cpp: naprog.qrc \
		notantiq.ico \
		notantiq.icns \
		images/open.png \
		images/help.png \
		images/print.png \
		images/pdf.png \
		images/find.png \
		images/lytexpdf.png \
		images/saveas.png \
		images/paste.png \
		images/save.png \
		images/configure.png \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/gabctopdf.png \
		images/utilities.png \
		images/exit.png \
		images/info.png \
		images/latexpdf.png \
		images/clean.png \
		help/helpindex-de.html
	/usr/bin/rcc -name naprog naprog.qrc -o qrc_naprog.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_naclefselect.h ui_naheaderwizard.h ui_nahelp.h ui_naprog.h ui_nasettings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_naclefselect.h ui_naheaderwizard.h ui_nahelp.h ui_naprog.h ui_nasettings.h
ui_naclefselect.h: naclefselect.ui
	/usr/bin/uic-qt4 naclefselect.ui -o ui_naclefselect.h

ui_naheaderwizard.h: naheaderwizard.ui
	/usr/bin/uic-qt4 naheaderwizard.ui -o ui_naheaderwizard.h

ui_nahelp.h: nahelp.ui
	/usr/bin/uic-qt4 nahelp.ui -o ui_nahelp.h

ui_naprog.h: naprog.ui
	/usr/bin/uic-qt4 naprog.ui -o ui_naprog.h

ui_nasettings.h: nasettings.ui
	/usr/bin/uic-qt4 nasettings.ui -o ui_nasettings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp naprog.h \
		nasyntax.h \
		nasettings.h \
		nahelp.h \
		ui_nahelp.h \
		namdi.h \
		naclefselect.h \
		naheaderwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

naclefselect.o: naclefselect.cpp naclefselect.h \
		ui_naclefselect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o naclefselect.o naclefselect.cpp

naheaderwizard.o: naheaderwizard.cpp naheaderwizard.h \
		ui_naheaderwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o naheaderwizard.o naheaderwizard.cpp

nahelp.o: nahelp.cpp nahelp.h \
		ui_nahelp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nahelp.o nahelp.cpp

namdi.o: namdi.cpp namdi.h \
		nasyntax.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o namdi.o namdi.cpp

naprog.o: naprog.cpp naprog.h \
		nasyntax.h \
		nasettings.h \
		nahelp.h \
		ui_nahelp.h \
		namdi.h \
		naclefselect.h \
		naheaderwizard.h \
		ui_naprog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o naprog.o naprog.cpp

nasettings.o: nasettings.cpp nasettings.h \
		ui_nasettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nasettings.o nasettings.cpp

nasyntax.o: nasyntax.cpp nasyntax.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nasyntax.o nasyntax.cpp

moc_naclefselect.o: moc_naclefselect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_naclefselect.o moc_naclefselect.cpp

moc_naheaderwizard.o: moc_naheaderwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_naheaderwizard.o moc_naheaderwizard.cpp

moc_nahelp.o: moc_nahelp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nahelp.o moc_nahelp.cpp

moc_namdi.o: moc_namdi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_namdi.o moc_namdi.cpp

moc_naprog.o: moc_naprog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_naprog.o moc_naprog.cpp

moc_nasettings.o: moc_nasettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nasettings.o moc_nasettings.cpp

moc_nasyntax.o: moc_nasyntax.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nasyntax.o moc_nasyntax.cpp

qrc_naprog.o: qrc_naprog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_naprog.o qrc_naprog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

