# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dg/Notatio-Antiqua

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dg/Notatio-Antiqua

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dg/Notatio-Antiqua/CMakeFiles /home/dg/Notatio-Antiqua/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dg/Notatio-Antiqua/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Notatio-Antiqua

# Build rule for target.
Notatio-Antiqua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Notatio-Antiqua
.PHONY : Notatio-Antiqua

# fast build rule for target.
Notatio-Antiqua/fast:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/build
.PHONY : Notatio-Antiqua/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/main.cpp.s
.PHONY : main.cpp.s

moc_naclefselect.o: moc_naclefselect.cxx.o
.PHONY : moc_naclefselect.o

# target to build an object file
moc_naclefselect.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naclefselect.cxx.o
.PHONY : moc_naclefselect.cxx.o

moc_naclefselect.i: moc_naclefselect.cxx.i
.PHONY : moc_naclefselect.i

# target to preprocess a source file
moc_naclefselect.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naclefselect.cxx.i
.PHONY : moc_naclefselect.cxx.i

moc_naclefselect.s: moc_naclefselect.cxx.s
.PHONY : moc_naclefselect.s

# target to generate assembly for a file
moc_naclefselect.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naclefselect.cxx.s
.PHONY : moc_naclefselect.cxx.s

moc_naheaderwizard.o: moc_naheaderwizard.cxx.o
.PHONY : moc_naheaderwizard.o

# target to build an object file
moc_naheaderwizard.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naheaderwizard.cxx.o
.PHONY : moc_naheaderwizard.cxx.o

moc_naheaderwizard.i: moc_naheaderwizard.cxx.i
.PHONY : moc_naheaderwizard.i

# target to preprocess a source file
moc_naheaderwizard.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naheaderwizard.cxx.i
.PHONY : moc_naheaderwizard.cxx.i

moc_naheaderwizard.s: moc_naheaderwizard.cxx.s
.PHONY : moc_naheaderwizard.s

# target to generate assembly for a file
moc_naheaderwizard.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naheaderwizard.cxx.s
.PHONY : moc_naheaderwizard.cxx.s

moc_nahelp.o: moc_nahelp.cxx.o
.PHONY : moc_nahelp.o

# target to build an object file
moc_nahelp.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nahelp.cxx.o
.PHONY : moc_nahelp.cxx.o

moc_nahelp.i: moc_nahelp.cxx.i
.PHONY : moc_nahelp.i

# target to preprocess a source file
moc_nahelp.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nahelp.cxx.i
.PHONY : moc_nahelp.cxx.i

moc_nahelp.s: moc_nahelp.cxx.s
.PHONY : moc_nahelp.s

# target to generate assembly for a file
moc_nahelp.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nahelp.cxx.s
.PHONY : moc_nahelp.cxx.s

moc_namdi.o: moc_namdi.cxx.o
.PHONY : moc_namdi.o

# target to build an object file
moc_namdi.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_namdi.cxx.o
.PHONY : moc_namdi.cxx.o

moc_namdi.i: moc_namdi.cxx.i
.PHONY : moc_namdi.i

# target to preprocess a source file
moc_namdi.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_namdi.cxx.i
.PHONY : moc_namdi.cxx.i

moc_namdi.s: moc_namdi.cxx.s
.PHONY : moc_namdi.s

# target to generate assembly for a file
moc_namdi.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_namdi.cxx.s
.PHONY : moc_namdi.cxx.s

moc_naprog.o: moc_naprog.cxx.o
.PHONY : moc_naprog.o

# target to build an object file
moc_naprog.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naprog.cxx.o
.PHONY : moc_naprog.cxx.o

moc_naprog.i: moc_naprog.cxx.i
.PHONY : moc_naprog.i

# target to preprocess a source file
moc_naprog.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naprog.cxx.i
.PHONY : moc_naprog.cxx.i

moc_naprog.s: moc_naprog.cxx.s
.PHONY : moc_naprog.s

# target to generate assembly for a file
moc_naprog.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_naprog.cxx.s
.PHONY : moc_naprog.cxx.s

moc_nasettings.o: moc_nasettings.cxx.o
.PHONY : moc_nasettings.o

# target to build an object file
moc_nasettings.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasettings.cxx.o
.PHONY : moc_nasettings.cxx.o

moc_nasettings.i: moc_nasettings.cxx.i
.PHONY : moc_nasettings.i

# target to preprocess a source file
moc_nasettings.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasettings.cxx.i
.PHONY : moc_nasettings.cxx.i

moc_nasettings.s: moc_nasettings.cxx.s
.PHONY : moc_nasettings.s

# target to generate assembly for a file
moc_nasettings.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasettings.cxx.s
.PHONY : moc_nasettings.cxx.s

moc_nasyntax.o: moc_nasyntax.cxx.o
.PHONY : moc_nasyntax.o

# target to build an object file
moc_nasyntax.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasyntax.cxx.o
.PHONY : moc_nasyntax.cxx.o

moc_nasyntax.i: moc_nasyntax.cxx.i
.PHONY : moc_nasyntax.i

# target to preprocess a source file
moc_nasyntax.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasyntax.cxx.i
.PHONY : moc_nasyntax.cxx.i

moc_nasyntax.s: moc_nasyntax.cxx.s
.PHONY : moc_nasyntax.s

# target to generate assembly for a file
moc_nasyntax.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/moc_nasyntax.cxx.s
.PHONY : moc_nasyntax.cxx.s

naclefselect.o: naclefselect.cpp.o
.PHONY : naclefselect.o

# target to build an object file
naclefselect.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naclefselect.cpp.o
.PHONY : naclefselect.cpp.o

naclefselect.i: naclefselect.cpp.i
.PHONY : naclefselect.i

# target to preprocess a source file
naclefselect.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naclefselect.cpp.i
.PHONY : naclefselect.cpp.i

naclefselect.s: naclefselect.cpp.s
.PHONY : naclefselect.s

# target to generate assembly for a file
naclefselect.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naclefselect.cpp.s
.PHONY : naclefselect.cpp.s

naheaderwizard.o: naheaderwizard.cpp.o
.PHONY : naheaderwizard.o

# target to build an object file
naheaderwizard.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naheaderwizard.cpp.o
.PHONY : naheaderwizard.cpp.o

naheaderwizard.i: naheaderwizard.cpp.i
.PHONY : naheaderwizard.i

# target to preprocess a source file
naheaderwizard.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naheaderwizard.cpp.i
.PHONY : naheaderwizard.cpp.i

naheaderwizard.s: naheaderwizard.cpp.s
.PHONY : naheaderwizard.s

# target to generate assembly for a file
naheaderwizard.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naheaderwizard.cpp.s
.PHONY : naheaderwizard.cpp.s

nahelp.o: nahelp.cpp.o
.PHONY : nahelp.o

# target to build an object file
nahelp.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nahelp.cpp.o
.PHONY : nahelp.cpp.o

nahelp.i: nahelp.cpp.i
.PHONY : nahelp.i

# target to preprocess a source file
nahelp.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nahelp.cpp.i
.PHONY : nahelp.cpp.i

nahelp.s: nahelp.cpp.s
.PHONY : nahelp.s

# target to generate assembly for a file
nahelp.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nahelp.cpp.s
.PHONY : nahelp.cpp.s

namdi.o: namdi.cpp.o
.PHONY : namdi.o

# target to build an object file
namdi.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/namdi.cpp.o
.PHONY : namdi.cpp.o

namdi.i: namdi.cpp.i
.PHONY : namdi.i

# target to preprocess a source file
namdi.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/namdi.cpp.i
.PHONY : namdi.cpp.i

namdi.s: namdi.cpp.s
.PHONY : namdi.s

# target to generate assembly for a file
namdi.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/namdi.cpp.s
.PHONY : namdi.cpp.s

naprog.o: naprog.cpp.o
.PHONY : naprog.o

# target to build an object file
naprog.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naprog.cpp.o
.PHONY : naprog.cpp.o

naprog.i: naprog.cpp.i
.PHONY : naprog.i

# target to preprocess a source file
naprog.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naprog.cpp.i
.PHONY : naprog.cpp.i

naprog.s: naprog.cpp.s
.PHONY : naprog.s

# target to generate assembly for a file
naprog.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/naprog.cpp.s
.PHONY : naprog.cpp.s

nasettings.o: nasettings.cpp.o
.PHONY : nasettings.o

# target to build an object file
nasettings.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasettings.cpp.o
.PHONY : nasettings.cpp.o

nasettings.i: nasettings.cpp.i
.PHONY : nasettings.i

# target to preprocess a source file
nasettings.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasettings.cpp.i
.PHONY : nasettings.cpp.i

nasettings.s: nasettings.cpp.s
.PHONY : nasettings.s

# target to generate assembly for a file
nasettings.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasettings.cpp.s
.PHONY : nasettings.cpp.s

nasyntax.o: nasyntax.cpp.o
.PHONY : nasyntax.o

# target to build an object file
nasyntax.cpp.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasyntax.cpp.o
.PHONY : nasyntax.cpp.o

nasyntax.i: nasyntax.cpp.i
.PHONY : nasyntax.i

# target to preprocess a source file
nasyntax.cpp.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasyntax.cpp.i
.PHONY : nasyntax.cpp.i

nasyntax.s: nasyntax.cpp.s
.PHONY : nasyntax.s

# target to generate assembly for a file
nasyntax.cpp.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/nasyntax.cpp.s
.PHONY : nasyntax.cpp.s

qrc_naprog.o: qrc_naprog.cxx.o
.PHONY : qrc_naprog.o

# target to build an object file
qrc_naprog.cxx.o:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/qrc_naprog.cxx.o
.PHONY : qrc_naprog.cxx.o

qrc_naprog.i: qrc_naprog.cxx.i
.PHONY : qrc_naprog.i

# target to preprocess a source file
qrc_naprog.cxx.i:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/qrc_naprog.cxx.i
.PHONY : qrc_naprog.cxx.i

qrc_naprog.s: qrc_naprog.cxx.s
.PHONY : qrc_naprog.s

# target to generate assembly for a file
qrc_naprog.cxx.s:
	$(MAKE) -f CMakeFiles/Notatio-Antiqua.dir/build.make CMakeFiles/Notatio-Antiqua.dir/qrc_naprog.cxx.s
.PHONY : qrc_naprog.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Notatio-Antiqua"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_naclefselect.o"
	@echo "... moc_naclefselect.i"
	@echo "... moc_naclefselect.s"
	@echo "... moc_naheaderwizard.o"
	@echo "... moc_naheaderwizard.i"
	@echo "... moc_naheaderwizard.s"
	@echo "... moc_nahelp.o"
	@echo "... moc_nahelp.i"
	@echo "... moc_nahelp.s"
	@echo "... moc_namdi.o"
	@echo "... moc_namdi.i"
	@echo "... moc_namdi.s"
	@echo "... moc_naprog.o"
	@echo "... moc_naprog.i"
	@echo "... moc_naprog.s"
	@echo "... moc_nasettings.o"
	@echo "... moc_nasettings.i"
	@echo "... moc_nasettings.s"
	@echo "... moc_nasyntax.o"
	@echo "... moc_nasyntax.i"
	@echo "... moc_nasyntax.s"
	@echo "... naclefselect.o"
	@echo "... naclefselect.i"
	@echo "... naclefselect.s"
	@echo "... naheaderwizard.o"
	@echo "... naheaderwizard.i"
	@echo "... naheaderwizard.s"
	@echo "... nahelp.o"
	@echo "... nahelp.i"
	@echo "... nahelp.s"
	@echo "... namdi.o"
	@echo "... namdi.i"
	@echo "... namdi.s"
	@echo "... naprog.o"
	@echo "... naprog.i"
	@echo "... naprog.s"
	@echo "... nasettings.o"
	@echo "... nasettings.i"
	@echo "... nasettings.s"
	@echo "... nasyntax.o"
	@echo "... nasyntax.i"
	@echo "... nasyntax.s"
	@echo "... qrc_naprog.o"
	@echo "... qrc_naprog.i"
	@echo "... qrc_naprog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

