Document: notantiq
Title: Debian notantiq Manual
Author: <insert document author here>
Abstract: This manual describes what notantiq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/notantiq/notantiq.sgml.gz

Format: postscript
Files: /usr/share/doc/notantiq/notantiq.ps.gz

Format: text
Files: /usr/share/doc/notantiq/notantiq.text.gz

Format: HTML
Index: /usr/share/doc/notantiq/html/index.html
Files: /usr/share/doc/notantiq/html/*.html
