var gpPublic;function createCookie(c,b,a){if(a){var e=new Date;e.setTime(e.getTime()+a*24*60*60*1E3);a="; expires="+e.toGMTString()}else a="";document.cookie=c+"="+b+a+"; path=/"}function readCookie(c){c+="=";for(var b=document.cookie.split(";"),a=0;a<b.length;a++){for(var e=b[a];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,e.length)}return false}function eraseCookie(c){createCookie(c,"",-1)}
function jPrep(c,b){b=typeof b=="undefined"?"gpreq=json&jsoncallback=?":b;c=strip_from(c,"#");c+=c.indexOf("?")==-1?"?":"&";return c+b}
function ajaxResponse(c){var b=false;for(i in c){var a=c[i];if(typeof gpresponse[a.DO]=="function")gpresponse[a.DO].call(this,a);else switch(a.DO){case "replace":$(a.SELECTOR).replaceWith(a.CONTENT);break;case "inner":$(a.SELECTOR).html(a.CONTENT);break;case "eval":eval(a.CONTENT);break;case "renameprep":RenamePrep();break;case "colorbox":b=true;$.fn.colorbox({opacity:0.75,html:a.CONTENT,open:true,maxWidth:"90%",minWidth:"300",minHeight:"300"});break;default:alert("nothing for: "+a.DO)}}if(!b)try{$.fn.colorbox.close()}catch(e){}$.fn.gpeasy.LiveJQ();
loaded()}
$(function(){var c="";c=IE7?"IE7CLASS":"STCLASS";$("body").addClass(c);eraseCookie("cookie_cmd");gpPublic=$.fn.gpeasy=function(){return this};gpPublic.jGoTo=function(b){loading();b=jPrep(b);$.getJSON(b,ajaxResponse)};gpPublic.cGoTo=function(b,a){var e;e=a?window.location.href:strip_from(b.href,"?");createCookie("cookie_cmd",encodeURIComponent(b.search),1);window.location=strip_from(e,"#")};gpPublic.post=function(b){loading();var a=$(b).closest("form"),e=jPrep(a.attr("action"));a=a.serialize();if(b.nodeName==
"INPUT")a+="&"+encodeURIComponent(b.name)+"="+encodeURIComponent(b.value);$.post(e,a,ajaxResponse,"json");return false};gpPublic.postC=function(b,a,e,f){a+="&verified="+readCookie("gpEasy");b=strip_from(b,"?");$.post(b,a,e,f)};gpPublic.LiveJQ=function(){$(".expand_child").unbind("mouseenter.live").unbind("mouseleave.live").bind("mouseenter.live",function(){$(this).addClass("expand");$(this).hasClass("simple_top")&&$(this).addClass("simple_top_hover")}).bind("mouseleave.live",function(){$(this).removeClass("expand").removeClass("simple_top_hover")})};
(function(){function b(a){$(a).filter("[method=post]").append('<input type="hidden" name="verified" value="'+readCookie("gpEasy")+'" />')}$().ajaxError(function(){alert("Error fetching response. Reload this page to continue.")});$("form").live("mousedown",function(){$this=$(this);if($this.data("gpForms")!="checked"){if(typeof this["return"]!=="undefined")this["return"].value=window.location;$this.data("gpForms","checked")}});$("input").live("click",function(){b(this.form);$this=$(this);var a=$this.attr("class");
a=strip_from(a," ");if(typeof gpinputs[a]=="function")return gpinputs[a].call(this);switch(a){case "gppost":case "gpajax":return gpPublic.post(this)}return true});$("form").live("submit",function(){b(this)});$.fn.gpeasy.LiveJQ();$("a[name]").live("click",function(a){var e=$(this).attr("name"),f=$(this).attr("rel");if(typeof gplinks[e]=="function")return gplinks[e].call(this,f,a);switch(e){case "tabs":tabs(this);break;case "remote":e=window.location.href;e=strip_from(e,"#");var g=jPrep(this.href,"gpreq=body");
g+="&in="+encodeURIComponent(e);$.fn.colorbox({opacity:0.75,iframe:true,href:g,minWidth:"90%",height:"90%",maxWidth:"850",onLoad:function(){document.body.scroll="no";document.body.style.overflow="hidden"},onCleanup:function(){document.body.scroll="auto";document.body.style.overflow=""}});break;case "ajax_box":$.fn.colorbox({opacity:0.75,href:jPrep(this.href,"gpreq=flush"),open:true,maxWidth:"90%",minWidth:"300",minHeight:"300"});break;case "inline_box":(g=$(f).find("form").get(0))&&$(this).find("input").each(function(j,
h){if(g[h.name])g[h.name].value=h.value});$.fn.colorbox({opacity:0.75,inline:true,href:f,open:true,maxWidth:"90%",minWidth:"300",minHeight:"300"});break;case "gpajax":$.fn.gpeasy.jGoTo(this.href);break;case "creq":$.fn.gpeasy.cGoTo(this,true);break;case "cnreq":$.fn.gpeasy.cGoTo(this,false);break;case "close_message":$(this).closest(".messages").slideUp();break;case "gallery":$(f==""?this:"a[rel="+f+"]").colorbox({opacity:0.75,maxWidth:"90%",maxHeight:"90%",resize:true,minWidth:"300",minHeight:"300"});
$.fn.colorbox.launch(this);break;default:return true}a.preventDefault();return false})})();$("body").trigger("gpReady")});function loading(){$("#loading").css({zIndex:"9001000"}).fadeTo(400,0.8)}function loaded(){$("#loading").clearQueue().hide()}function tabs(c){$(c.parentNode).find("a").removeClass("selected").each(function(b,a){var e=get_hash(a.href);e&&$("#"+e).hide()});d=get_hash(c.href);$("#"+d).show();c.className="selected";$.colorbox.resize()}function get_hash(c){return strip_to(c,"#")}
function strip_to(c,b){var a=c.indexOf(b);if(a>0)return c.substr(a+1);return false}function strip_from(c,b){var a=c.indexOf(b);if(a>0)c=c.substr(0,a);return c};